// frontend/app/admin/page.tsx
"use client"

import { useState, useEffect, useCallback } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import {
    AlertCircle, ArrowLeft, Shield, Users, CalendarDays,
    Plus, Pencil, Trash2, Search, X, CheckCircle, Lock, Eye, EyeOff
} from "lucide-react"
import Link from "next/link"

// ── Types ─────────────────────────────────────────────────────────────────────

interface AdminUser {
    id: string
    username: string
    email: string
    perms: number
    createdAt: string
}

interface AdminEvent {
    id: number
    title: string
    date: string
    location: string | null
    createdBy: string
    creatorName: string | null
    private: boolean
    color: string | null
}

type Tab = "users" | "events"

// ── Component ─────────────────────────────────────────────────────────────────

export default function AdminPage() {
    const [tab, setTab] = useState<Tab>("users")
    const [userSearch, setUserSearch] = useState("")
    const [eventSearch, setEventSearch] = useState("")

    // Users state
    const [users, setUsers] = useState<AdminUser[]>([])
    const [usersLoading, setUsersLoading] = useState(true)

    // Events state
    const [events, setEvents] = useState<AdminEvent[]>([])
    const [eventsLoading, setEventsLoading] = useState(true)

    // User form dialog
    const [userDialogOpen, setUserDialogOpen] = useState(false)
    const [editingUser, setEditingUser] = useState<AdminUser | null>(null)
    const [userForm, setUserForm] = useState({ username: "", email: "", password: "", perms: 0 })
    const [showPassword, setShowPassword] = useState(false)
    const [userSaving, setUserSaving] = useState(false)
    const [userError, setUserError] = useState("")

    // Delete dialogs
    const [deleteUserOpen, setDeleteUserOpen] = useState(false)
    const [deletingUserId, setDeletingUserId] = useState<string | null>(null)
    const [deleteEventOpen, setDeleteEventOpen] = useState(false)
    const [deletingEventId, setDeletingEventId] = useState<number | null>(null)
    const [deleteLoading, setDeleteLoading] = useState(false)

    const [globalError, setGlobalError] = useState("")

    // ── Fetch ──────────────────────────────────────────────────────────────────

    const fetchUsers = useCallback(async () => {
        setUsersLoading(true)
        try {
            const res = await fetch("/api/admin/users")
            if (res.ok) setUsers(await res.json())
            else setGlobalError("Failed to load users")
        } finally {
            setUsersLoading(false)
        }
    }, [])

    const fetchEvents = useCallback(async () => {
        setEventsLoading(true)
        try {
            const res = await fetch("/api/admin/events")
            if (res.ok) setEvents(await res.json())
            else setGlobalError("Failed to load events")
        } finally {
            setEventsLoading(false)
        }
    }, [])

    useEffect(() => { fetchUsers() }, [fetchUsers])
    useEffect(() => { fetchEvents() }, [fetchEvents])

    // ── User CRUD ──────────────────────────────────────────────────────────────

    function openCreateUser() {
        setEditingUser(null)
        setUserForm({ username: "", email: "", password: "", perms: 0 })
        setUserError("")
        setShowPassword(false)
        setUserDialogOpen(true)
    }

    function openEditUser(user: AdminUser) {
        setEditingUser(user)
        setUserForm({ username: user.username, email: user.email, password: "", perms: user.perms })
        setUserError("")
        setShowPassword(false)
        setUserDialogOpen(true)
    }

    async function saveUser() {
        setUserError("")
        if (!userForm.username.trim() || !userForm.email.trim()) {
            setUserError("Username and email are required")
            return
        }
        if (!editingUser && !userForm.password) {
            setUserError("Password is required for new users")
            return
        }
        if (userForm.password && userForm.password.length < 8) {
            setUserError("Password must be at least 8 characters")
            return
        }

        setUserSaving(true)
        try {
            const payload = editingUser
                ? { id: editingUser.id, username: userForm.username, email: userForm.email, perms: userForm.perms, newPassword: userForm.password || undefined }
                : { username: userForm.username, email: userForm.email, password: userForm.password, perms: userForm.perms }

            const res = await fetch("/api/admin/users", {
                method: editingUser ? "PUT" : "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(payload),
            })
            const data = await res.json()
            if (!res.ok) {
                setUserError(data.error || "Failed to save user")
            } else {
                await fetchUsers()
                setUserDialogOpen(false)
            }
        } finally {
            setUserSaving(false)
        }
    }

    async function deleteUser() {
        if (!deletingUserId) return
        setDeleteLoading(true)
        try {
            const res = await fetch(`/api/admin/users?id=${deletingUserId}`, { method: "DELETE" })
            if (res.ok) {
                await fetchUsers()
                setDeleteUserOpen(false)
                setDeletingUserId(null)
            }
        } finally {
            setDeleteLoading(false)
        }
    }

    // ── Event CRUD ─────────────────────────────────────────────────────────────

    async function deleteEvent() {
        if (!deletingEventId) return
        setDeleteLoading(true)
        try {
            const res = await fetch(`/api/admin/events?id=${deletingEventId}`, { method: "DELETE" })
            if (res.ok) {
                await fetchEvents()
                setDeleteEventOpen(false)
                setDeletingEventId(null)
            }
        } finally {
            setDeleteLoading(false)
        }
    }

    // ── Filtered lists ─────────────────────────────────────────────────────────

    const filteredUsers = users.filter(u =>
        u.username.toLowerCase().includes(userSearch.toLowerCase()) ||
        u.email.toLowerCase().includes(userSearch.toLowerCase())
    )

    const filteredEvents = events.filter(e =>
        e.title.toLowerCase().includes(eventSearch.toLowerCase()) ||
        e.creatorName?.toLowerCase().includes(eventSearch.toLowerCase()) ||
        e.location?.toLowerCase().includes(eventSearch.toLowerCase())
    )

    // ── Render ─────────────────────────────────────────────────────────────────

    return (
        <div className="min-h-screen bg-background text-foreground">
            {/* Header */}
            <div className="border-b border-border/50 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <Link href="/calendar">
                        <Button variant="ghost" size="icon-sm">
                            <ArrowLeft className="w-4 h-4" />
                        </Button>
                    </Link>
                    <Shield className="w-5 h-5 text-amber-500" />
                    <h1 className="text-lg font-semibold">Admin Panel</h1>
                </div>
                <Link href="/account">
                    <Button variant="ghost" size="sm">Account</Button>
                </Link>
            </div>

            {globalError && (
                <div className="mx-6 mt-4 flex items-center gap-2 p-3 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded-md">
                    <AlertCircle className="w-4 h-4 flex-shrink-0" /> {globalError}
                </div>
            )}

            {/* Stats */}
            <div className="px-6 pt-6 grid grid-cols-2 gap-4 max-w-4xl mx-auto">
                <Card>
                    <CardContent className="pt-5 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center">
                            <Users className="w-5 h-5 text-blue-500" />
                        </div>
                        <div>
                            <div className="text-2xl font-bold">{users.length}</div>
                            <div className="text-sm text-muted-foreground">Total Users</div>
                        </div>
                    </CardContent>
                </Card>
                <Card>
                    <CardContent className="pt-5 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-violet-500/10 flex items-center justify-center">
                            <CalendarDays className="w-5 h-5 text-violet-500" />
                        </div>
                        <div>
                            <div className="text-2xl font-bold">{events.length}</div>
                            <div className="text-sm text-muted-foreground">Total Events</div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* Tabs */}
            <div className="px-6 pt-6 max-w-4xl mx-auto">
                <div className="flex gap-1 bg-muted/50 p-1 rounded-lg w-fit mb-6">
                    <button
                        onClick={() => setTab("users")}
                        className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${tab === "users" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"}`}
                    >
                        <Users className="w-3.5 h-3.5 inline mr-1.5" />Users
                    </button>
                    <button
                        onClick={() => setTab("events")}
                        className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${tab === "events" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"}`}
                    >
                        <CalendarDays className="w-3.5 h-3.5 inline mr-1.5" />Events
                    </button>
                </div>

                {/* ── Users Tab ── */}
                {tab === "users" && (
                    <Card>
                        <CardHeader>
                            <div className="flex items-center justify-between">
                                <div>
                                    <CardTitle>Users</CardTitle>
                                    <CardDescription>Manage user accounts and permissions</CardDescription>
                                </div>
                                <Button size="sm" onClick={openCreateUser}>
                                    <Plus className="w-4 h-4 mr-1" /> New User
                                </Button>
                            </div>
                            <div className="relative mt-2">
                                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
                                <Input className="pl-8 h-8 text-sm" placeholder="Search users…" value={userSearch} onChange={e => setUserSearch(e.target.value)} />
                                {userSearch && <button onClick={() => setUserSearch("")} className="absolute right-2 top-1/2 -translate-y-1/2"><X className="w-3 h-3 text-muted-foreground" /></button>}
                            </div>
                        </CardHeader>
                        <CardContent>
                            {usersLoading ? (
                                <p className="text-sm text-muted-foreground">Loading…</p>
                            ) : filteredUsers.length === 0 ? (
                                <p className="text-sm text-muted-foreground">No users found.</p>
                            ) : (
                                <div className="flex flex-col divide-y divide-border/50">
                                    {filteredUsers.map(user => (
                                        <div key={user.id} className="flex items-center justify-between py-3">
                                            <div className="flex items-center gap-3">
                                                <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-xs font-bold uppercase">
                                                    {user.username[0]}
                                                </div>
                                                <div>
                                                    <div className="text-sm font-medium flex items-center gap-1.5">
                                                        {user.username}
                                                        {user.perms >= 999 && (
                                                            <span className="text-[10px] bg-amber-500/10 text-amber-500 px-1.5 py-0.5 rounded-full font-medium">Admin</span>
                                                        )}
                                                    </div>
                                                    <div className="text-xs text-muted-foreground">{user.email}</div>
                                                </div>
                                            </div>
                                            <div className="flex items-center gap-1">
                                                <Button variant="ghost" size="icon-sm" onClick={() => openEditUser(user)}>
                                                    <Pencil className="w-3.5 h-3.5" />
                                                </Button>
                                                <Button
                                                    variant="ghost" size="icon-sm"
                                                    className="text-destructive hover:text-destructive"
                                                    onClick={() => { setDeletingUserId(user.id); setDeleteUserOpen(true) }}
                                                >
                                                    <Trash2 className="w-3.5 h-3.5" />
                                                </Button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </CardContent>
                    </Card>
                )}

                {/* ── Events Tab ── */}
                {tab === "events" && (
                    <Card>
                        <CardHeader>
                            <div className="flex items-center justify-between">
                                <div>
                                    <CardTitle>All Events</CardTitle>
                                    <CardDescription>View and delete any event across all users</CardDescription>
                                </div>
                            </div>
                            <div className="relative mt-2">
                                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
                                <Input className="pl-8 h-8 text-sm" placeholder="Search events…" value={eventSearch} onChange={e => setEventSearch(e.target.value)} />
                                {eventSearch && <button onClick={() => setEventSearch("")} className="absolute right-2 top-1/2 -translate-y-1/2"><X className="w-3 h-3 text-muted-foreground" /></button>}
                            </div>
                        </CardHeader>
                        <CardContent>
                            {eventsLoading ? (
                                <p className="text-sm text-muted-foreground">Loading…</p>
                            ) : filteredEvents.length === 0 ? (
                                <p className="text-sm text-muted-foreground">No events found.</p>
                            ) : (
                                <div className="flex flex-col divide-y divide-border/50">
                                    {filteredEvents.map(event => (
                                        <div key={event.id} className="flex items-center justify-between py-3 gap-3">
                                            <div className="flex items-center gap-3 min-w-0">
                                                <div className={`w-2 h-8 rounded-full flex-shrink-0 ${event.color || "bg-blue-500"}`} />
                                                <div className="min-w-0">
                                                    <div className="text-sm font-medium truncate flex items-center gap-1.5">
                                                        {event.title}
                                                        {event.private && <Lock className="w-3 h-3 text-muted-foreground flex-shrink-0" />}
                                                    </div>
                                                    <div className="text-xs text-muted-foreground">
                                                        by {event.creatorName ?? "Unknown"} · {new Date(event.date).toLocaleDateString()}
                                                        {event.location && ` · ${event.location}`}
                                                    </div>
                                                </div>
                                            </div>
                                            <Button
                                                variant="ghost" size="icon-sm"
                                                className="text-destructive hover:text-destructive flex-shrink-0"
                                                onClick={() => { setDeletingEventId(event.id); setDeleteEventOpen(true) }}
                                            >
                                                <Trash2 className="w-3.5 h-3.5" />
                                            </Button>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </CardContent>
                    </Card>
                )}
            </div>

            {/* ── User Form Dialog ── */}
            <Dialog open={userDialogOpen} onOpenChange={setUserDialogOpen}>
                <DialogContent className="sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                            {editingUser ? <><Pencil className="w-4 h-4" /> Edit User</> : <><Plus className="w-4 h-4" /> New User</>}
                        </DialogTitle>
                    </DialogHeader>
                    <div className="flex flex-col gap-4 py-1">
                        <div className="flex flex-col gap-1.5">
                            <Label htmlFor="adm-username">Username</Label>
                            <Input id="adm-username" value={userForm.username} onChange={e => setUserForm(f => ({ ...f, username: e.target.value }))} autoFocus />
                        </div>
                        <div className="flex flex-col gap-1.5">
                            <Label htmlFor="adm-email">Email</Label>
                            <Input id="adm-email" type="email" value={userForm.email} onChange={e => setUserForm(f => ({ ...f, email: e.target.value }))} />
                        </div>
                        <div className="flex flex-col gap-1.5">
                            <Label htmlFor="adm-password">
                                Password {editingUser && <span className="text-muted-foreground font-normal">(leave blank to keep current)</span>}
                            </Label>
                            <div className="relative">
                                <Input
                                    id="adm-password"
                                    type={showPassword ? "text" : "password"}
                                    placeholder={editingUser ? "New password…" : "Min. 8 characters"}
                                    value={userForm.password}
                                    onChange={e => setUserForm(f => ({ ...f, password: e.target.value }))}
                                    className="pr-9"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(v => !v)}
                                    className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                                >
                                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                                </button>
                            </div>
                        </div>
                        <div className="flex flex-col gap-1.5">
                            <Label htmlFor="adm-perms">Role</Label>
                            <div className="flex gap-2">
                                <button
                                    onClick={() => setUserForm(f => ({ ...f, perms: 0 }))}
                                    className={`flex-1 py-2 rounded-md border text-sm font-medium transition-colors ${userForm.perms < 999 ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:border-muted-foreground"}`}
                                >
                                    User
                                </button>
                                <button
                                    onClick={() => setUserForm(f => ({ ...f, perms: 999 }))}
                                    className={`flex-1 py-2 rounded-md border text-sm font-medium transition-colors ${userForm.perms >= 999 ? "border-amber-500 bg-amber-500/10 text-amber-500" : "border-border text-muted-foreground hover:border-muted-foreground"}`}
                                >
                                    <Shield className="w-3.5 h-3.5 inline mr-1" />Admin
                                </button>
                            </div>
                        </div>
                        {userError && (
                            <div className="flex items-center gap-2 p-3 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded-md">
                                <AlertCircle className="w-4 h-4 flex-shrink-0" /> {userError}
                            </div>
                        )}
                    </div>
                    <DialogFooter>
                        <Button variant="ghost" onClick={() => setUserDialogOpen(false)} disabled={userSaving}>Cancel</Button>
                        <Button onClick={saveUser} disabled={userSaving}>
                            {userSaving ? "Saving…" : editingUser ? "Update" : "Create"}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* ── Delete User Dialog ── */}
            <Dialog open={deleteUserOpen} onOpenChange={setDeleteUserOpen}>
                <DialogContent className="sm:max-w-sm">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2 text-destructive">
                            <AlertCircle className="w-5 h-5" /> Delete User
                        </DialogTitle>
                    </DialogHeader>
                    <p className="text-sm text-muted-foreground">
                        This will permanently delete the user and all their data. This cannot be undone.
                    </p>
                    <DialogFooter>
                        <Button variant="ghost" onClick={() => setDeleteUserOpen(false)} disabled={deleteLoading}>Cancel</Button>
                        <Button variant="destructive" onClick={deleteUser} disabled={deleteLoading}>
                            {deleteLoading ? "Deleting…" : "Delete"}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* ── Delete Event Dialog ── */}
            <Dialog open={deleteEventOpen} onOpenChange={setDeleteEventOpen}>
                <DialogContent className="sm:max-w-sm">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2 text-destructive">
                            <AlertCircle className="w-5 h-5" /> Delete Event
                        </DialogTitle>
                    </DialogHeader>
                    <p className="text-sm text-muted-foreground">
                        This will permanently delete this event and all its RSVPs. This cannot be undone.
                    </p>
                    <DialogFooter>
                        <Button variant="ghost" onClick={() => setDeleteEventOpen(false)} disabled={deleteLoading}>Cancel</Button>
                        <Button variant="destructive" onClick={deleteEvent} disabled={deleteLoading}>
                            {deleteLoading ? "Deleting…" : "Delete"}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    )
}

// frontend-svelte/src/routes/admin/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiFetch } from '$lib/api';
  import { auth } from '$lib/stores';
  import { goto } from '$app/navigation';
  import type { User, Event } from '$lib/types';
  import { ArrowLeft, Shield, Users, CalendarDays, Plus, Pencil, Trash2, Search, X, Eye, EyeOff } from 'lucide-svelte';

  type Tab = 'users' | 'events';
  let tab: Tab = 'users';

  let users:  User[]  = [];
  let events: Event[] = [];
  let usersLoading  = true;
  let eventsLoading = true;
  let userSearch  = '';
  let eventSearch = '';
  let globalError = '';

  // User dialog
  let userDialogOpen = false;
  let editingUser: User | null = null;
  let userForm = { username: '', email: '', password: '', perms: 0 };
  let showPassword = false;
  let userSaving = false;
  let userError  = '';

  // Delete
  let deleteUserOpen  = false;
  let deletingUserId: string | null = null;
  let deleteEventOpen = false;
  let deletingEventId: number | null = null;
  let deleteLoading = false;

  onMount(async () => {
    if (($auth.user?.perms ?? 0) < 999) { goto('/calendar'); return; }
    fetchUsers();
    fetchEvents();
  });

  async function fetchUsers() {
    usersLoading = true;
    try { users = await apiFetch<User[]>('/api/admin/users'); }
    catch { globalError = 'Failed to load users'; }
    finally { usersLoading = false; }
  }

  async function fetchEvents() {
    eventsLoading = true;
    try { events = await apiFetch<Event[]>('/api/admin/events'); }
    catch { globalError = 'Failed to load events'; }
    finally { eventsLoading = false; }
  }

  function openCreateUser() {
    editingUser = null;
    userForm = { username: '', email: '', password: '', perms: 0 };
    userError = ''; showPassword = false; userDialogOpen = true;
  }

  function openEditUser(u: User) {
    editingUser = u;
    userForm = { username: u.username, email: u.email, password: '', perms: u.perms };
    userError = ''; showPassword = false; userDialogOpen = true;
  }

  async function saveUser() {
    userError = '';
    if (!userForm.username.trim() || !userForm.email.trim()) { userError = 'Username and email are required'; return; }
    if (!editingUser && !userForm.password) { userError = 'Password is required for new users'; return; }
    if (userForm.password && userForm.password.length < 8) { userError = 'Password must be at least 8 characters'; return; }

    userSaving = true;
    try {
      const payload = editingUser
        ? { id: editingUser.id, username: userForm.username, email: userForm.email, perms: userForm.perms, new_password: userForm.password || undefined }
        : { username: userForm.username, email: userForm.email, password: userForm.password, perms: userForm.perms };

      await apiFetch('/api/admin/users', {
        method: editingUser ? 'PUT' : 'POST',
        body: JSON.stringify(payload)
      });
      await fetchUsers();
      userDialogOpen = false;
    } catch (err: unknown) {
      userError = err instanceof Error ? err.message : 'Failed to save user';
    } finally { userSaving = false; }
  }

  async function deleteUser() {
    if (!deletingUserId) return;
    deleteLoading = true;
    try {
      await apiFetch(`/api/admin/users?id=${deletingUserId}`, { method: 'DELETE' });
      await fetchUsers();
      deleteUserOpen = false; deletingUserId = null;
    } finally { deleteLoading = false; }
  }

  async function deleteEvent() {
    if (!deletingEventId) return;
    deleteLoading = true;
    try {
      await apiFetch(`/api/admin/events?id=${deletingEventId}`, { method: 'DELETE' });
      await fetchEvents();
      deleteEventOpen = false; deletingEventId = null;
    } finally { deleteLoading = false; }
  }

  $: filteredUsers  = users.filter(u =>
    u.username.toLowerCase().includes(userSearch.toLowerCase()) ||
    u.email.toLowerCase().includes(userSearch.toLowerCase())
  );
  $: filteredEvents = events.filter(e =>
    e.title.toLowerCase().includes(eventSearch.toLowerCase()) ||
    (e.creator_name ?? '').toLowerCase().includes(eventSearch.toLowerCase())
  );

  const INPUT = 'h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/30 transition';
</script>

<div class="min-h-screen bg-background text-foreground">
  <!-- Header -->
  <header class="border-b border-border/50 px-6 py-4 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <a href="/calendar" class="p-1.5 rounded hover:bg-muted transition"><ArrowLeft class="w-4 h-4" /></a>
      <Shield class="w-5 h-5 text-amber-400" />
      <h1 class="text-lg font-semibold">Admin Panel</h1>
    </div>
    <a href="/account" class="h-8 px-3 rounded-md text-sm hover:bg-muted transition inline-flex items-center">Account</a>
  </header>

  {#if globalError}
    <div class="mx-6 mt-4 p-3 text-sm text-red-400 bg-red-500/10 border border-red-500/20 rounded-md">{globalError}</div>
  {/if}

  <!-- Stats -->
  <div class="px-6 pt-6 grid grid-cols-2 gap-4 max-w-4xl mx-auto">
    <div class="rounded-xl bg-card ring-1 ring-foreground/10 p-5 flex items-center gap-3">
      <div class="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center"><Users class="w-5 h-5 text-blue-400" /></div>
      <div><div class="text-2xl font-bold">{users.length}</div><div class="text-sm text-muted-foreground">Total Users</div></div>
    </div>
    <div class="rounded-xl bg-card ring-1 ring-foreground/10 p-5 flex items-center gap-3">
      <div class="w-10 h-10 rounded-lg bg-violet-500/10 flex items-center justify-center"><CalendarDays class="w-5 h-5 text-violet-400" /></div>
      <div><div class="text-2xl font-bold">{events.length}</div><div class="text-sm text-muted-foreground">Total Events</div></div>
    </div>
  </div>

  <!-- Tabs -->
  <div class="px-6 pt-6 max-w-4xl mx-auto">
    <div class="flex gap-1 bg-muted/50 p-1 rounded-lg w-fit mb-6">
      {#each (['users', 'events'] as Tab[]) as t}
        <button
          on:click={() => (tab = t)}
          class="px-4 py-1.5 rounded-md text-sm font-medium transition
                 {tab === t ? 'bg-card shadow text-foreground' : 'text-muted-foreground hover:text-foreground'}"
        >
          {t === 'users' ? 'Users' : 'Events'}
        </button>
      {/each}
    </div>

    <!-- Users Tab -->
    {#if tab === 'users'}
      <div class="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <div class="p-6 border-b border-border/50 flex flex-col gap-3">
          <div class="flex items-center justify-between">
            <div>
              <h2 class="font-semibold">Users</h2>
              <p class="text-sm text-muted-foreground">Manage accounts and permissions</p>
            </div>
            <button on:click={openCreateUser}
              class="inline-flex items-center gap-1 h-8 px-3 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/80 transition">
              <Plus class="w-3.5 h-3.5" /> New User
            </button>
          </div>
          <div class="relative">
            <Search class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
            <input class="{INPUT} pl-8" placeholder="Search users…" bind:value={userSearch} />
            {#if userSearch}
              <button on:click={() => (userSearch = '')} class="absolute right-2.5 top-1/2 -translate-y-1/2">
                <X class="w-3 h-3 text-muted-foreground" />
              </button>
            {/if}
          </div>
        </div>
        <div class="divide-y divide-border/50">
          {#if usersLoading}
            <p class="p-4 text-sm text-muted-foreground">Loading…</p>
          {:else if filteredUsers.length === 0}
            <p class="p-4 text-sm text-muted-foreground">No users found.</p>
          {:else}
            {#each filteredUsers as u}
              <div class="flex items-center justify-between px-6 py-3">
                <div class="flex items-center gap-3">
                  <div class="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-xs font-bold uppercase">{u.username[0]}</div>
                  <div>
                    <div class="text-sm font-medium flex items-center gap-1.5">
                      {u.username}
                      {#if u.perms >= 999}
                        <span class="text-[10px] bg-amber-500/10 text-amber-400 px-1.5 py-0.5 rounded-full">Admin</span>
                      {/if}
                    </div>
                    <div class="text-xs text-muted-foreground">{u.email}</div>
                  </div>
                </div>
                <div class="flex gap-1">
                  <button on:click={() => openEditUser(u)} class="p-1.5 rounded hover:bg-muted transition"><Pencil class="w-3.5 h-3.5" /></button>
                  <button on:click={() => { deletingUserId = u.id; deleteUserOpen = true; }} class="p-1.5 rounded hover:bg-muted text-destructive transition"><Trash2 class="w-3.5 h-3.5" /></button>
                </div>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    {/if}

    <!-- Events Tab -->
    {#if tab === 'events'}
      <div class="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <div class="p-6 border-b border-border/50 flex flex-col gap-3">
          <div>
            <h2 class="font-semibold">All Events</h2>
            <p class="text-sm text-muted-foreground">View and delete any event across all users</p>
          </div>
          <div class="relative">
            <Search class="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
            <input class="{INPUT} pl-8" placeholder="Search events…" bind:value={eventSearch} />
          </div>
        </div>
        <div class="divide-y divide-border/50">
          {#if eventsLoading}
            <p class="p-4 text-sm text-muted-foreground">Loading…</p>
          {:else if filteredEvents.length === 0}
            <p class="p-4 text-sm text-muted-foreground">No events found.</p>
          {:else}
            {#each filteredEvents as e}
              <div class="flex items-center justify-between px-6 py-3 gap-3">
                <div class="flex items-center gap-3 min-w-0">
                  <div class="w-2 h-8 rounded-full flex-shrink-0" style="background:{e.color ?? '#6366f1'}"></div>
                  <div class="min-w-0">
                    <div class="text-sm font-medium truncate">{e.title}</div>
                    <div class="text-xs text-muted-foreground">by {e.creator_name ?? 'Unknown'} · {new Date(e.date).toLocaleDateString()}</div>
                  </div>
                </div>
                <button on:click={() => { deletingEventId = e.id; deleteEventOpen = true; }} class="p-1.5 rounded hover:bg-muted text-destructive transition flex-shrink-0">
                  <Trash2 class="w-3.5 h-3.5" />
                </button>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    {/if}
  </div>
</div>

<!-- User Form Dialog -->
{#if userDialogOpen}
  <div class="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" role="dialog">
    <div class="w-full max-w-md bg-card rounded-xl ring-1 ring-foreground/10 shadow-xl p-6 flex flex-col gap-5">
      <div class="flex items-center justify-between">
        <h2 class="font-semibold">{editingUser ? 'Edit User' : 'New User'}</h2>
        <button on:click={() => (userDialogOpen = false)} class="p-1 rounded hover:bg-muted transition"><X class="w-4 h-4" /></button>
      </div>
      <div class="flex flex-col gap-4">
        <div class="flex flex-col gap-1.5">
          <label class="text-sm font-medium">Username</label>
          <input class={INPUT} bind:value={userForm.username} />
        </div>
        <div class="flex flex-col gap-1.5">
          <label class="text-sm font-medium">Email</label>
          <input class={INPUT} type="email" bind:value={userForm.email} />
        </div>
        <div class="flex flex-col gap-1.5">
          <label class="text-sm font-medium">Password {#if editingUser}<span class="text-muted-foreground font-normal">(leave blank to keep)</span>{/if}</label>
          <div class="relative">
            <input class="{INPUT} pr-10" type={showPassword ? 'text' : 'password'} bind:value={userForm.password} placeholder={editingUser ? 'New password…' : 'Min. 8 characters'} />
            <button type="button" on:click={() => (showPassword = !showPassword)} class="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground">
              {#if showPassword}<EyeOff class="w-4 h-4" />{:else}<Eye class="w-4 h-4" />{/if}
            </button>
          </div>
        </div>
        <div class="flex flex-col gap-1.5">
          <label class="text-sm font-medium">Role</label>
          <div class="flex gap-2">
            <button type="button" on:click={() => (userForm.perms = 0)}
              class="flex-1 py-2 rounded-md border text-sm font-medium transition
                     {userForm.perms < 999 ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground'}">
              User
            </button>
            <button type="button" on:click={() => (userForm.perms = 999)}
              class="flex-1 py-2 rounded-md border text-sm font-medium transition
                     {userForm.perms >= 999 ? 'border-amber-500 bg-amber-500/10 text-amber-400' : 'border-border text-muted-foreground'}">
              Admin
            </button>
          </div>
        </div>
        {#if userError}
          <div class="p-3 text-sm text-red-400 bg-red-500/10 border border-red-500/20 rounded-md">{userError}</div>
        {/if}
      </div>
      <div class="flex gap-2 justify-end">
        <button on:click={() => (userDialogOpen = false)} disabled={userSaving}
          class="h-9 px-4 rounded-md border border-border text-sm hover:bg-muted transition">Cancel</button>
        <button on:click={saveUser} disabled={userSaving}
          class="h-9 px-4 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/80 disabled:opacity-50 transition">
          {userSaving ? 'Saving…' : editingUser ? 'Update' : 'Create'}
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- Delete User Dialog -->
{#if deleteUserOpen}
  <div class="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" role="dialog">
    <div class="w-full max-w-sm bg-card rounded-xl ring-1 ring-foreground/10 shadow-xl p-6 flex flex-col gap-4">
      <h2 class="font-semibold text-destructive">Delete User</h2>
      <p class="text-sm text-muted-foreground">This will permanently delete the user and all their data. This cannot be undone.</p>
      <div class="flex gap-2 justify-end">
        <button on:click={() => (deleteUserOpen = false)} disabled={deleteLoading}
          class="h-9 px-4 rounded-md border border-border text-sm hover:bg-muted transition">Cancel</button>
        <button on:click={deleteUser} disabled={deleteLoading}
          class="h-9 px-4 rounded-md bg-destructive/10 text-destructive text-sm font-medium hover:bg-destructive/20 disabled:opacity-50 transition">
          {deleteLoading ? 'Deleting…' : 'Delete'}
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- Delete Event Dialog -->
{#if deleteEventOpen}
  <div class="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" role="dialog">
    <div class="w-full max-w-sm bg-card rounded-xl ring-1 ring-foreground/10 shadow-xl p-6 flex flex-col gap-4">
      <h2 class="font-semibold text-destructive">Delete Event</h2>
      <p class="text-sm text-muted-foreground">This will permanently delete this event and all its RSVPs. This cannot be undone.</p>
      <div class="flex gap-2 justify-end">
        <button on:click={() => (deleteEventOpen = false)} disabled={deleteLoading}
          class="h-9 px-4 rounded-md border border-border text-sm hover:bg-muted transition">Cancel</button>
        <button on:click={deleteEvent} disabled={deleteLoading}
          class="h-9 px-4 rounded-md bg-destructive/10 text-destructive text-sm font-medium hover:bg-destructive/20 disabled:opacity-50 transition">
          {deleteLoading ? 'Deleting…' : 'Delete'}
        </button>
      </div>
    </div>
  </div>
{/if}
